#!/bin/bash

[ -z "$2" ] && echo "Run dt-install-sandbox-software to call this script" && exit 1

# This script is called via the dt-install-sandbox-software command.
# Do not run it directly.  Further, this is called prior to the
# sandbox environment being loaded into the shell so any variables
# needed from the defaults.sh (or other env file) must be setup
# manually.

export VSCSB_SANDBOX=$1  # root of the sandbox
export VSCSB_TOP=$2      # root of the primary git project
SB_ENV_FILE=$3            # name of the environment file to use
export VSCSB_NAME=`dirname $VSCSB_SANDBOX`
[ -z "$SB_ENV_FILE" ] && SB_ENV_FILE=defaults.sh


. $VSCSB_TOP/sandbox/$SB_ENV_FILE

# Install node if specified with VSCSB_NODE_VER
[ -n "$VSCSB_NODE_VER" -a ! -L $VSCSB_SANDBOX/node ] && dt-get-software -V $VSCSB_NODE_VER node $VSCSB_SANDBOX

# Install yarn if specified with VSCSB_YARN_VER
[ -n "$VSCSB_YARN_VER" -a ! -L $VSCSB_SANDBOX/yarn ] && dt-get-software -V $VSCSB_YARN_VER yarn $VSCSB_SANDBOX

cd $VSCSB_SANDBOX
[ ! -d codestream-components ] && echo "CLoning codestream-components" && git clone git@github.com:teamcodestream/codestream-components
[ ! -d codestream-lsp-agent ] && echo "Cloning codestream-lsp-agent" && git clone git@github.com:teamcodestream/codestream-lsp-agent

exit 0
