#!/bin/bash

[ -z "$2" ] && echo "Run dt-install-sandbox-software to call this script" && exit 1

# This script is called via the dt-install-sandbox-software command.
# Do not run it directly.  Further, this is called prior to the
# sandbox environment being loaded into the shell so any variables
# needed from the defaults.sh (or other env file) must be setup
# manually.

export ATOM_SANDBOX=$1  # root of the sandbox
export ATOM_TOP=$2      # root of the primary git project
SB_ENV_FILE=$3            # name of the environment file to use
export ATOM_NAME=`dirname $ATOM_SANDBOX`
[ -z "$SB_ENV_FILE" ] && SB_ENV_FILE=defaults.sh


. $ATOM_TOP/sandbox/$SB_ENV_FILE

# Install node if specified with ATOM_NODE_VER
[ -n "$ATOM_NODE_VER" -a ! -L $ATOM_SANDBOX/node ] && dt-get-software -V $ATOM_NODE_VER node $ATOM_SANDBOX

# Install yarn if specified with ATOM_YARN_VER
[ -n "$ATOM_YARN_VER" -a ! -L $ATOM_SANDBOX/yarn ] && dt-get-software -V $ATOM_YARN_VER yarn $ATOM_SANDBOX



# Put custom one-time only software installations here (such as git clones of additional repos,
# other software packages that will live in the sandbox, etc...).
#
# Note that there is no sandbox process, other than a first time install, that exeutes this hook.

cd $ATOM_SANDBOX
# [ ! -d codestream-components ] && echo "CLoning codestream-components" && git clone git@github.com:teamcodestream/codestream-components
# [ ! -d codestream-lsp-agent ] && echo "Cloning codestream-lsp-agent" && git clone git@github.com:teamcodestream/codestream-lsp-agent

exit 0
