namespace CodeStream.VisualStudio.Properties
{
    public static class SolutionInfo
    {
        /// <summary>
        /// This was generated by a tool (build process)
        /// </summary>
        public const string Version = "0.51.0.0";

        /// <summary>
        /// This was generated by a tool (build process)
        /// </summary>
        public const string BuildEnv = "";
    }
}
