namespace CodeStream.VisualStudio.Core.Properties {
	public static class SolutionInfo {
		/// <summary>
		/// This was generated by a tool (build process)
		/// </summary>
		public const string Version = "8.3.6.0";

		/// <summary>
		/// This was generated by a tool (build process)
		/// </summary>
		public const string BuildEnv = "";
	}
}
