// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeStream.VisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSPackageCommandTopMenuString = "fa7d279c-5194-450a-8842-10680454e362";
        public const string guidVSPackageCommandTopMenuCmdSetString = "9f33235e-3a5c-42bc-b519-d888652f972b";
        public const string guidVSPackageCommandCodeWindowContextMenuCmdSetString = "0f33235e-3a5c-42bc-b519-d888652f972c";
        public const string guidImagesString = "f2c8ef6d-3257-4e0a-8ae0-ef6298dd22c5";
        public static Guid guidVSPackageCommandTopMenu = new Guid(guidVSPackageCommandTopMenuString);
        public static Guid guidVSPackageCommandTopMenuCmdSet = new Guid(guidVSPackageCommandTopMenuCmdSetString);
        public static Guid guidVSPackageCommandCodeWindowContextMenuCmdSet = new Guid(guidVSPackageCommandCodeWindowContextMenuCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodeStreamTopLevelMenu = 0x1020;
        public const int CodeStreamGroupForCommands = 0x1021;
        public const int WebViewToggleCommandId = 0x0100;
        public const int AuthenticationCommandId = 0x0200;
        public const int MyGroupForEditorCommands = 0x1023;
        public const int AddCodemarkCommandId = 0x0300;
        public const int logo = 0x0001;
        public const int auth = 0x0002;
        public const int empty3 = 0x0003;
        public const int empty4 = 0x0004;
        public const int empty5 = 0x0005;
        public const int empty6 = 0x0006;
    }
}
